name: Core Package

on: [push]
#  release:
#    types: [created]

jobs:
  csharp:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: out/csharp
    strategy:
      matrix:
        dotnet-version: ["5.0.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{matrix.dotnet-version}}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{matrix.dotnet-version}}
          source-url: https://nuget.pkg.github.com/giovanebribeiro/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack --configuration Release  --no-restore
      - name: Publish
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}
