name: Core Package

on: [push]
#  release:
#    types: [created]

jobs:
  nodejs:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: out/nodejs
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Setup npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" >> ./.npmrc
      - name: Install dependencies
        run: npm install
      - name: Build 
        run: npm run build
      - name: Publish
        run: npm publish
  csharp:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: out/csharp
    strategy:
      matrix:
        dotnet-version: ["5.0.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{matrix.dotnet-version}}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{matrix.dotnet-version}}
          source-url: https://nuget.pkg.github.com/giovanebribeiro/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Pack
        run: dotnet pack --configuration Release  --no-restore
      - name: Publish
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
